odev3/WebProje/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Models;

namespace WebProje.Controllers
{
  
    public class AdminController : Controller
    {
        // GET: Admin
        private HastaneEntities1 db = new HastaneEntities1();
        public ActionResult Index() 
        {
            return View();
        }
        public ActionResult DoktorlarGoruntule()
        {
            var doktor = db.Doktor.ToList();
            return View(doktor);
        }
       
        public ActionResult RandevuEkle()
        {     
            ViewBag.Randevu_Doktor = new SelectList(db.Doktor,"Doktor_ID","Doktor_Adi");
            return View();
        }
        [HttpPost]
        public ActionResult RandevuEkle(Randevu model)
        {
            if(ModelState.IsValid)
            {
                db.Randevu.Add(model);
                db.SaveChanges();
                return RedirectToAction("RandevuEkle");
            }
            ViewBag.Randevu_Doktor = new SelectList(db.Doktor, "Doktor_ID", "Doktor_Adi");
            return View();
        }
        public ActionResult DoktorEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DoktorEkle(Doktor model)
        {
            if(ModelState.IsValid)
            {
                HttpPostedFileBase resim = Request.Files["pict"] as HttpPostedFileBase;
                string path = HttpContext.Server.MapPath("~/Content/Resimler/" + resim.FileName);
                resim.SaveAs(path);
                model.Doktor_Resim = "~/Content/Resimler/" + resim.FileName;
                db.Doktor.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();
        }
      
    }
}

odev3/WebProje/Views/Admin/DoktorEkle.cshtml
@model WebProje.Models.Doktor

@{
    ViewBag.Title = "DoktorEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DoktorEkle</h2>

@using (Html.BeginForm("DoktorEkle", "Admin",FormMethod.Post, new {@enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doktor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Doktor_Adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doktor_Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doktor_Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doktor_Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doktor_Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doktor_Soyadi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doktor_DogumTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doktor_DogumTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doktor_DogumTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doktor_Bilgi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doktor_Bilgi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doktor_Bilgi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doktor_Resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("pict", new { htmlAttributes = new { @class = "form-control",@type="file" } })
                @Html.ValidationMessageFor(model => model.Doktor_Resim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

odev3/WebProje/Views/Admin/DoktorlarGoruntule.cshtml
@model IEnumerable<WebProje.Models.Doktor>
<div class="container body-content"
@{
    ViewBag.Title = "Doktorlar Goruntule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<p>
    @Html.ActionLink("Geri Dön", "Index", "Admin")


</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Doktor_Adi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doktor_Soyadi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doktor_DogumTarih)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doktor_Bilgi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doktor_Resim)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Doktor_Adi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doktor_Soyadi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doktor_DogumTarih)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doktor_Bilgi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doktor_Resim)
        </td>
    </tr>
}

</table>
    </div>

odev3/WebProje/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container body-content">
    <h2>Admin Paneli</h2>
    @Html.ActionLink("Doktor Ekle", "DoktorEkle", "Admin") <br />
    @Html.ActionLink("Doktorları Goruntule", "DoktorlarGoruntule", "Admin") <br />
    @Html.ActionLink("Randevu Ekle", "RandevuEkle", "Admin")<br />

</div>

odev3/WebProje/Views/Admin/RandevuEkle.cshtml
@model WebProje.Models.Randevu

<div class=" container body-content">
    @{
        ViewBag.Title = "RandevuEkle";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>Randevu Ekle</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
         
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Randevu_Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Randevu_Tarih, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Randevu_Tarih, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Randevu_Doktor, "Randevu_Doktor", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Randevu_Doktor", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Randevu_Doktor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>